Mark BROKEN for ELF: gcc  -o scheme cmpauxmd.o cmpint.o artutl.o avltree.o bignum.o bigprm.o bitstr.o  boot.o char.o comutl.o daemon.o debug.o dfloat.o error.o extern.o fasload.o fix num.o flonum.o generic.o hooks.o hunk.o intern.o interp.o intprm.o list.o lookpr m.o lookup.o obstack.o option.o osscheme.o ostty.o outf.o prim.o primutl.o prmco n.o ptrvec.o purutl.o regex.o rgxprim.o step.o storage.o string.o syntax.o syspr im.o term.o transact.o utils.o vector.o wind.o fasdump.o gcloop.o memmag.o purif y.o intext.o ux.o uxctty.o uxenv.o uxfile.o uxfs.o uxio.o uxproc.o uxsig.o uxsoc k.o uxterm.o uxtop.o uxtrap.o uxtty.o uxutil.o prosenv.o prosfile.o prosfs.o pro sio.o prosproc.o prospty.o prosterm.o prostty.o pruxenv.o pruxfs.o pruxio.o prux sock.o usrdef.o x11base.o x11term.o x11graph.o x11color.o tparam.o tterm.o  missing.o   -L/usr/X11R6/lib    -lX11 -ltermcap -lm cmpauxmd.o(.text+0x5a): undefined reference to `_Ext_Stack_Pointer' cmpauxmd.o(.text+0x60): undefined reference to `_Free' cmpauxmd.o(.text+0x7d): undefined reference to `_utility_table' cmpauxmd.o(.text+0x8a): undefined reference to `_Free' cmpauxmd.o(.text+0x98): undefined reference to `_Ext_Stack_Pointer'
git-svn-id: svn+ssh://svn.freebsd.org/ports/head@13982 aed309b6-a8cd-e111-996c-001c23d10e55