devel/caf: fix build on GCC architectures
Some files require including sys/types.h before other headers:
/usr/include/netinet/ip.h:227:2: error: 'u_short' does not name a type; did you mean 'short'?
  227 |  u_short  ippseudo_len; /* protocol length */
      |  ^~~~~~~
      |  short

PR:		245364
Approved by:	leres (maintainer)
MFH:		2020Q2 (build fix blanket)