Remove prototype, so it still compiles under CURRENT killfile.c:58: conflicting types for `strnstr'
git-svn-id: svn+ssh://svn.freebsd.org/ports/head@48762 aed309b6-a8cd-e111-996c-001c23d10e55