devel/lazygit: unbreak on aarch64
# github.com/jesseduffield/pty
vendor/github.com/jesseduffield/pty/pty_freebsd.go:50:20: undefined: fiodgnameArg
vendor/github.com/jesseduffield/pty/pty_freebsd.go:63:12: undefined: _C_SPECNAMELEN
vendor/github.com/jesseduffield/pty/pty_freebsd.go:66:9: undefined: fiodgnameArg

Add the missing ztypes_freebsd_arm64.go file for aarch64

PR:		245013
Approved by:	meta (maintainer), manu (mentor, implicit)