Add missed #include "support.h" into uploadWizard.c, so that there is no undefined reference to screem_show_warning() function.
Prompted by:	John Merryweather Cooper <john_m_cooper@yahoo.com>


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@51374 aed309b6-a8cd-e111-996c-001c23d10e55