- Bump PORTREVISION after boost update - While here trim header - Mark broken since it failes to build with new boost
I/usr/local/include/python2.7 -c src/wrapper/id3.cpp -o temp.freebsd-9.1-RELEASE-amd64-2.7/src/wrapper/id3.o
src/wrapper/id3.cpp: In function 'void exposeID3()':
src/wrapper/id3.cpp:215:8: error: no matching function for call to 'boost::python::class_<TagLib::ID3v2::Tag, boost::noncopyable_::noncopyable, boost::python::bases<TagLib::Tag> >::def(const char [7], <unresolved overloaded function type>)'
src/wrapper/id3.cpp:215:8: note: candidates are:


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@312704 aed309b6-a8cd-e111-996c-001c23d10e55