- Add NOT_FOR_ARCHS= amd64 due to build problems on amd64:
[javac] bittyrant/work/BitTyrant/org/gudy/azureus2/ui/swt/views/ \
  IView.java:23: package org.eclipse.swt.widgets does not exist
[javac] import org.eclipse.swt.widgets.Composite;
[javac]                               ^
[javac] bittyrant/work/BitTyrant/org/gudy/azureus2/ui/swt/views/ \
  AbstractIView.java:39: cannot find symbol
[javac] symbol  : class Composite
[javac] location: class org.gudy.azureus2.ui.swt.views.AbstractIView
[javac]   public void initialize(Composite composite){
[javac]                          ^
...
[javac] 100 errors
BUILD FAILED
bittyrant/work/BitTyrant/build.xml:34: Compile failed; see the compiler
error output for details.

Reported by:	pointyhat


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@301410 aed309b6-a8cd-e111-996c-001c23d10e55