Sysutils/fusefs-kmod requires also userland sources
	Fusefs-kmod says it requires kernel sources, but it also requires
	userland sources:

	Warning: Object directory not changed from original /var/ports/usr/ports/sysutils/fusefs-kmod/work/fuse4bsd-0.3.9-pre1/mount_fusefs
	cc -O2 -fno-strict-aliasing -pipe -I/usr/src/sbin/mount -I../include -c mount_fusefs.c
					  ^^^^^^^^^^^^^^^^^^^^^^
	mount_fusefs.c:50:21: mntopts.h: No such file or directory
	mount_fusefs.c:57: error: elements of array `mopts' have incomplete type

PR:		ports/116196
Submitted by:	Edwin Groothuis <edwin@mavetju.org>
Approved by:	maintainer timeout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@200717 aed309b6-a8cd-e111-996c-001c23d10e55