multimedia/obs-studio: fix build on powerpc64 elfv2
obs-studio uses SSE unconditionally, but Clang can't doesn't have good enough SSE -> Altivec translation layer, like GCC does:
In file included from /wrkdirs/usr/ports/multimedia/obs-studio/work/obs-studio-25.0.1/libobs/graphics/../util/sse-intrin.h:63:
In file included from /usr/lib/clang/10.0.0/include/xmmintrin.h:13:
/usr/lib/clang/10.0.0/include/mmintrin.h:50:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Use GCC on powerpc64.